{% set data= load_setup_py_data() %}

package:
    name: ts-logging-and-reporting
    version: {{ data.get('version') }}

source:
    path: ../

build:
    noarch: python
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
    string: "py{{ PY_VER | replace('.', '') }}{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"

test:
    requires:
        - ts-conda-build =0.5
    source_files:
        - pyproject.toml
        - python
        - tests
    commands:
        - pytest

requirements:
    host:
        - pip
        - python {{ python }}
        - setuptools
        - setuptools_scm
    build:
        - python {{ python }}
        - setuptools
        - setuptools_scm
    run:
        - python {{ python }}
        - setuptools
        - setuptools_scm
        - requests
        - pandas
        - numpy
        - astroplan
        - astropy
        - fastapi
        - ipython
        - pydantic
        - uvicorn
        - conda-forge::rubin-scheduler =3
        - rubin-nights =0.8
        - schedview =0.20
        - rubin-sim =2
        - bokeh =3
        - lsst-efd-client =0.12
        - scikit-learn
        - psycopg2 =2.9
        - astropy-iers-data
